### ISSUE TITLE
[incompatible] Dashloader (half compatible)

### ISSUE THREAD

**Issue by MissGamerz** [PepperCode1/Continuity#10]
** The Problem**
this will half work when dashloader takes its first cache this will work fine and nothing will seem wrong, its only on resource reload dashloader seems to break this mod and any blocks this mod has touched. I think I understand why this is a thing.

** Possible work around**
hook into dashloader (it has a API) on resource reload events and remove its cache to force dashloader to re-cache everything properly i worked with another dev who just delete the cache directly (config/QuantumFusion/Dashloader) then allow the resource reload to continue

**Comment by AsyncBanana** [comment]
I am pretty sure this mod uses BakedModels, so that is why there is this incompatibility.

> Most mods should work fine, but when they don't they are often horrifically broken with many models missing. Most of the incompatibilities are down to custom implementations of BakedModel.

([Dashloader Curseforge](https://www.curseforge.com/minecraft/mc-mods/dashloader))

According to my basic scanning of the Dashloader wiki, there should be a way to fix this, but it would require Dashloader specific code

**Comment by PepperCode1** [comment]
DashLoader version 3.0 and up should be fully compatible with Continuity.
