### ISSUE TITLE
Some weird stuff with with Faithful 32x resource pack

### ISSUE THREAD

**Issue by JumperREDACTED** [PepperCode1/Continuity#18]
With Continuity:
![2021-10-21_10 00 46](https://user-images.githubusercontent.com/83337894/138236603-c3ef1ec6-1707-458e-a962-e4ac11a60553.png)

Without Continuity
![2021-10-21_10 02 59](https://user-images.githubusercontent.com/83337894/138236644-65722da0-864d-40b7-a141-7db2d5b0ab38.png)

The resource pack in question:
https://faithful.team/faithful-1-17/

Logs:
[latest.log](https://github.com/PepperCode1/Continuity/files/7387239/latest.log)

**Comment by JumperREDACTED** [comment]
Ok it only happens when I use *both* [CMT Overhaul v3.1](https://www.curseforge.com/minecraft/texture-packs/connected-textures-mod-ctm-overhaul) and Faithful x32

**Comment by PepperCode1** [comment]
The exact same thing happens on Optifine, meaning this is not a bug and instead a pack conflict. Optifine CTM does not provide automatic connected texture generation capabilities - you cannot expect connected textures for the Faithful quartz ore texture to show up, because they do not exist. CTM Overhaul provides its own quartz ore CTM, which is actually used. The only way to resolve this is to either disable one of the packs or make your own version/find a version of CTM Overhaul that uses Faithful textures.
