### ISSUE TITLE
Update to 1.19.3

### ISSUE THREAD

**Issue by ghost** [PepperCode1/Continuity#207]
I have made a new issue as the old one has been abandoned and locked.

Continuity doesn't work correctly when trying to use it in 1.19.3. Continuity needs to have a proper update for 1.19.3.

**Comment by DreamStanMan** [comment]
I am quite confident that this will get closed as well, but that is just because of the laziness of the mod owner who doesn't want to work on a mod that they chose to provide to us.

I am not saying that mod owners have to deliver a new update every version, however Pepper was supposedly promising updates which have not happened due to indolence.

I respect mod owners, but Pepper isn't a very helpful nor respectful mod owner at that.

**Comment by PepperCode1** [comment]
Thank you for the feedback.
The old issue is not abandoned. It was locked because no further discussion was necessary. Duplicate of #189.

**Comment by aisukuma** [comment]
pepper does not owe you anything you’re just acting entitled and impatient. 

Join the Discord server as alpha versions exist there.

**Comment by ghost** [comment]
I worded my original comment poorly and speculated a lot more than I should have, but I feel as though locking the discussion that I made to let you know that your mod has issues with the latest versions is unnecessary. People could have listed logs and or anything else important in that issue to work out the issue.

**Comment by Julienraptor01** [comment]
> I worded my original comment poorly and speculated a lot more than I should have, but I feel as though locking the discussion that I made to let you know that your mod has issues with the latest versions is unnecessary. People could have listed logs and or anything else important in that issue to work out the issue.

Nothing was important, everything was known, join the discord for more info and alpha versions.

This issue should be locked as well to prevent unnecessary discussions btw
