### ISSUE TITLE
Crash randomly happens on opening inventory

### ISSUE THREAD

**Issue by ChromaPIE** [PepperCode1/Continuity#218]
There's a quite low possibility that the game crashes (shows REI crash screen. You can still go back into the game by pressing ESC but item and entity rendering are already broken. You gotta reboot the game to make it return to normal) upon showing inventories (or upon trying to render items for REI/EMI).

I'm no pro to this but it seems to be related to Continuity and Indium and/or REI/EMI (I switched from EMI to REI trying to solve the problem but it's still there).

Crash report: https://pastebin.com/NsAdCftY

I don't know the actual cause of it bc it happens so randomly and honestly the chance is small. But it's quite annoying and never fails to play a good jumpscare. If Continuity is not causing it please let me know which repo is the best for this issue to be submitted to.

**Comment by TheVillain-Inc** [comment]
Ahoy! 

Can confirm an issue between REI and Continuity. 

Crash only happens when I have both REI and Continuity, searched for 'hay' in the REI search bar - crash on "ha". Does not crash on the Minecraft Creative search bar

 Log below:

[crash-2024-12-29_13.12.14-client.txt](https://github.com/user-attachments/files/18269700/crash-2024-12-29_13.12.14-client.txt)

**Comment by PepperCode1** [comment]
That is not an issue between REI and Continuity or an issue with either mod. Some other mod's custom item model is returning a null quad list, which it should not be doing (possibly the same situation as #575, which is a Tetra/Forgified Fabric API bug). This issue tracker is not the place to debug that.

This report is almost two years old, so I will close it. If it happens again, open a new issue.
