### ISSUE TITLE
Breaks item texture of Prefab mod!!!

### ISSUE THREAD

**Issue by earthseekerx** [PepperCode1/Continuity#23]
After installing the mod in my world, the item textures from the prefab mod was...corrupted?
![2021-11-18_10 40 31](https://user-images.githubusercontent.com/45335253/142356136-83eedf47-070d-41af-ad24-c990c73b3635.png)
Please reply with any additional information as and when needed.

**Comment by FwuffyPetsOwO** [comment]
1) you are using several other mods, please narrow down this issue to the minimum number of mods that causes this issue, since mods may affect things in ways we do not anticipate
2) send a log file after you have done that. logs are found in the .minecraft/logs folder, we will probably need latest.log
3) is this issue only in the REI screen or is it present when an item is in the vanilla inventory as well? if it's only in REI, then it's almost certainly an issue with how REI handles item rendering, not with either this mod or Prefab mod

**Comment by PepperCode1** [comment]
A lot of development of Continuity has happened since November, so please test again with the latest version of all mods that you were using.

**Comment by PepperCode1** [comment]
Closing as there has not been a response from the author.
