### ISSUE TITLE
Sprite names starting with `assets/minecraft/` are not parsed correctly

### ISSUE THREAD

**Issue by razorchase49** [PepperCode1/Continuity#246]
Hello,
When using Continuity with a BDcraft, which has both animated textures and CTM models for Blocks of Redstone, the blocks do not connect. They connect just fine with OptiFine, but when I use Continuity, even with no other mods besides the Fabric API, it's as if the Blocks of Redstone are not registered correctly. I do not know if this happens Continuity does not support animated textures at all, or if it just doesn't support those using the OptiFine models.
I'm on Minecraft 1.19,4, using Fabric Loader 0.14.19, Fabric API 0.78.0, and Continuity 3.0.0 Beta 2.
Two screenshots are attached, one is with Continuity installed without the Redstone blocks connected, the other is with OptiFine with the blocks connected.
![2023-04-14_17 05 01](https://user-images.githubusercontent.com/19761194/232165482-10822ad8-768c-418c-b1c5-5d57521e0008.png)
![2023-04-14_17 08 25](https://user-images.githubusercontent.com/19761194/232165497-19277e83-3bf2-4d79-b8a8-3bd7984fd87f.png)

**Comment by PepperCode1** [comment]
This does not have anything to do with animated textures. The issue is that Optifine supports `matchTiles` and `tiles` that start with `assets/minecraft/`, whereas Continuity does not. Specifically only the redstone block CTM file in this pack uses `assets/minecraft/`, so it does not work with Continuity. The next update will fix this.
