### ISSUE TITLE
Square language. 1.20  3.0 beta-2

### ISSUE THREAD

**Issue by drakosoldier298** [PepperCode1/Continuity#261]
https://mclo.gs/obEZDTG Error log incase its needed.

![image](https://github.com/PepperCode1/Continuity/assets/30358222/ccc05623-43b8-451d-ac77-1008696234bb)

i mean its immersive to have the square language but i cant see what to do.

After testing *just* continuity, it seems to be an interaction with one of my many other mods. i dont have time to test currently but if i find what ill report back. till then ima have this here for anyone else.

**Comment by PepperCode1** [comment]
The main error:
`
java.lang.ClassCastException: class io.github.fourmisain.stitch.impl.StitchImpl$SpritesStage cannot be cast to class net.minecraft.class_7766$class_7767
`

Whichever mod has this class needs to be updated or removed.

**Comment by PepperCode1** [comment]
I finally found what this "stitch" mod is. Its source and the conflicting mixin can be found [here](https://github.com/Fourmisain/DirTNT/blob/1.19/stitch/src/main/java/io/github/fourmisain/stitch/mixin/SpriteLoaderMixin.java). This mod `Overwrite`s a method that Continuity injects into. Continuity looks for the first `thenApply` in this method and wraps its `Function` argument. This mod adds another `thenApply` before the one that Continuity should modify, and since this new `thenApply`'s argument has different generic types than the ones Continuity expects, it causes a `ClassCastException` when Continuity's code runs. It is possible for this mod to not use an `Overwrite`, so I will not be adding compatibility for it. I have also not ever heard of this mod before now. Report this issue [here](https://github.com/Fourmisain/DirTNT/issues).
