### ISSUE TITLE
Idea: make the Mod cause a crash when Sodium in installed, but Indium not.

### ISSUE THREAD

**Issue by schnow265** [PepperCode1/Continuity#279]
As the title says, I would like to make the mod cause a crash when Indium is not detected, but sodium is not.

I tried it, and managed to write this snippet found attached
[Indionite.txt](https://github.com/PepperCode1/Continuity/files/12013244/Indionite.txt)
, which causes a crash under the called criteria:

It would be one extra file, and just one more line in the **ContinuityClient.java** file.

**Comment by PepperCode1** [comment]
I have not done this because I do not want to directly depend on the presence of Indium, especially when it finally became fully unnecessary in 1.20. It is not possible to detect whether a renderer exists during mod initialization, but I can try to find the earliest point where the renderer is guaranteed to be initialized and crash the game if one is not present.

**Comment by PepperCode1** [comment]
The issue with the approach I described in the above comment is that the user would still need to check the log to see the crash reason. Users don't check logs and may still not understand what to do even if they do open the log, so I don't see a point in this suggestion. Regardless Sodium should be getting native FRAPI support soon.

**Comment by Poopooracoocoo** [comment]
Has jar-in-jar-ing No Indium been considered? Assuming Continuity 3.0.0-beta4 would release before Sodium 0.6
