### ISSUE TITLE
Remove render layer limitations in block.properties

### ISSUE THREAD

**Issue by muzikbike** [PepperCode1/Continuity#302]
It's impossible to change the render layer of many blocks via block.properties, presumably to make x-raying more difficult. This is, however, ultimately redundant due to the fact that many other resource pack methods can be used to achieve the same effect (e.g. replacing the models of certain blocks, or retexturing some blocks such as grass blocks which already use cutout rendering and themselves cull solid blocks). For the sake of creative liberty, it might be advisable to lift these restrictions - if someone is willing to install a mod that allows for extra texture pack customizability in order to exploit block.properties, they could just as easily install a mod or vanilla resource pack that grants them an unfair advantage anyway.

**Comment by PepperCode1** [comment]
This was done in all versions between and including the original version that added `block.properties` support and 2.0.1. Some packs broke because the limitations were removed so they were added back in 2.0.2. However, the `disableSolidCheck` boolean property was added (also in 2.0.2) to allow disabling the limitations manually. Add `disableSolidCheck=true` to remove all limitations.

As a bonus, Continuity's `block.properties` respects block state properties unlike OptiFine's.
