### ISSUE TITLE
Not working with other texturepacks

### ISSUE THREAD

**Issue by LostIntelligence** [PepperCode1/Continuity#35]
No matter what priority i place other textures at they seem to always override the connected textures.

**Comment by PepperCode1** [comment]
Log? Resource packs you tested with? Please provide some context.

**Comment by FwuffyPetsOwO** [comment]
1. Make sure you are using the latest version.
2. If you are using Sodium, you must install Indium for the mod to work correctly. It can be downloaded here: https://modrinth.com/mod/indium.
3. Enable the default packs (continuity/default, continuity/glass_pane_culling_fix) in the resource pack menu.
4. Check if you have incompatible mods installed from the list below. Do not remove them yet, but instead update them to their latest version and see if your issue is resolved. If not, then remove them.
- MoreMCMeta
- Essential

**Comment by LostIntelligence** [comment]
![2021-12-13_10 24 24](https://user-images.githubusercontent.com/80392200/145785868-68f8a127-debe-42fe-93ba-07902168bc91.png)
![2021-12-13_10 24 12](https://user-images.githubusercontent.com/80392200/145785894-64ba2b38-888a-47c6-8e31-a53c27e2a984.png)

**Comment by LostIntelligence** [comment]
I don't know if this is intended behavior i normally expect that the continuity textures completely override the rest as they are the top entry.

**Comment by PepperCode1** [comment]
The default pack never overrides the connected textures. It detects if the glass texture has been replaced, and since it has been, it disables the default glass connected textures. GeruDoku does not contain connected textures, so you will need to find or create an addon that adds them.
