### ISSUE TITLE
glass texture not connecting 

### ISSUE THREAD

**Issue by creamcitykitty** [PepperCode1/Continuity#365]
When I play minecraft with Continuity My glass textures won't connect Please fix this for 1.20.4

**Comment by YukiAyase** [comment]
Please send your log file located in **.minecraft/logs**. filename is **"latest"**

**Comment by DrAGoniPenguin** [comment]
Crash Report: https://mclo.gs/BfFG3TI
Latest Log: https://mclo.gs/WUBElyw

As you see, it appears to be from continuity.mixins.json:SpriteLoaderMixin
continuity.mixins.json:SpriteLoaderMixin from mod continuity -> net.minecraft.class_7766: ....
I dunno how Continuity or the fabric api works, so leaving this for you fabric guys.

Noting that the MoreCulling/Extra mods are also having something going wrong with glass textures.
https://github.com/FxMorin/MoreCullingExtra/issues/13

<details open>
<summary>Tested with: </summary>
<br>
  Fabric 0.15.6 Installation  
  fabric-api-0.95.3+1.20.4  
  continuity-3.0.0-beta.3+1.20.1  
  ~~indium-1.0.28+mc1.20.4~~  
  ~~sodium-fabric-mc1.20.3-0.5.5~~  
</details>
Same error occurs if Indium and Sodium are removed (strikethrough)

All mods/loader versions should be the latest release except for sodium due to many incompatibilitiies as of now with other mods.

**Comment by YukiAyase** [comment]
> Crash Report: https://mclo.gs/BfFG3TI Latest Log: https://mclo.gs/WUBElyw
> 
> As you see, it appears to be from continuity.mixins.json:SpriteLoaderMixin continuity.mixins.json:SpriteLoaderMixin from mod continuity -> net.minecraft.class_7766: .... I dunno how Continuity or the fabric api works, so leaving this for you fabric guys.
> 
> Noting that the MoreCulling/Extra mods are also having something going wrong with glass textures. [FxMorin/MoreCullingExtra#13](https://github.com/FxMorin/MoreCullingExtra/issues/13)
> 
> Tested with:
> 
> Fabric 0.15.6 Installation fabric-api-0.95.3+1.20.4 continuity-3.0.0-beta.3+1.20.1 ~~indium-1.0.28+mc1.20.4~~ ~~sodium-fabric-mc1.20.3-0.5.5~~
> Same error occurs if Indium and Sodium are removed (strikethrough)
> All mods/loader versions should be the latest release except for sodium due to many incompatibilitiies as of now with other mods.

Only putting the error from the log isn't really gonna help a lot
**And please create your own thread about this issue**

**Comment by DrAGoniPenguin** [comment]
> > Crash Report: https://mclo.gs/BfFG3TI Latest Log: https://mclo.gs/WUBElyw
> > As you see, it appears to be from continuity.mixins.json:SpriteLoaderMixin continuity.mixins.json:SpriteLoaderMixin from mod continuity -> net.minecraft.class_7766: .... I dunno how Continuity or the fabric api works, so leaving this for you fabric guys.
> > Noting that the MoreCulling/Extra mods are also having something going wrong with glass textures. [FxMorin/MoreCullingExtra#13](https://github.com/FxMorin/MoreCullingExtra/issues/13)
> > Tested with:
> > Fabric 0.15.6 Installation fabric-api-0.95.3+1.20.4 continuity-3.0.0-beta.3+1.20.1 ~indium-1.0.28+mc1.20.4~ ~sodium-fabric-mc1.20.3-0.5.5~
> > Same error occurs if Indium and Sodium are removed (strikethrough)
> > All mods/loader versions should be the latest release except for sodium due to many incompatibilitiies as of now with other mods.
> 
> Only putting the error from the log isn't really gonna help a lot **And please create your own thread about this issue**

Yeah sorry, thought this was related to this issue since several mods are also crashing at the glass texture mixin injection after updating 1.20.4
Attached log because of your request to author.

**Comment by PepperCode1** [comment]
OP did not provide enough information. @DrAGoniPenguin is using Continuity for 1.20.1 on 1.20.4, which will not work.
