### ISSUE TITLE
Not working on 1.18.1

### ISSUE THREAD

**Issue by MillzyDev** [PepperCode1/Continuity#37]
#### I recently installed this mod, selected the `continuity/default` texture pack. and nothing has happened...

![image](https://user-images.githubusercontent.com/64277238/145729492-b41b4410-b98f-43b6-a255-26aeef859a1e.png)

#### any help would be greatly appreciated

**Comment by FwuffyPetsOwO** [comment]
1. Make sure you are using the latest version.
2. If you are using Sodium, you must install Indium for the mod to work correctly. It can be downloaded here: https://modrinth.com/mod/indium.
3. Enable the default packs (continuity/default, continuity/glass_pane_culling_fix) in the resource pack menu.
4. Check if you have incompatible mods installed from the list below. Do not remove them yet, but instead update them to their latest version and see if your issue is resolved. If not, then remove them.
- MoreMCMeta
- Essential

**Comment by MillzyDev** [comment]
Ah that makes sense, I have sodium installed

**Comment by KlutzyBubbles** [comment]
> 1. Make sure you are using the latest version.
> 2. If you are using Sodium, you must install Indium for the mod to work correctly. It can be downloaded here: https://modrinth.com/mod/indium.
> 3. Enable the default packs (continuity/default, continuity/glass_pane_culling_fix) in the resource pack menu.
> 4. Check if you have incompatible mods installed from the list below. Do not remove them yet, but instead update them to their latest version and see if your issue is resolved. If not, then remove them.
> 
> * MoreMCMeta
> * Essential

Given how popular sodium is, would it be worthwhile to add this to the readme and/or descriptions on the mod download sites? This happened to me too, I just gave up and assumed the mod was broken.

**Comment by SqrtMz** [comment]
Well, i have sodium, indium and this mod installed, and worked perfectly until i deleted the options.txt from .minecraft due problems with very old versions, after that, the mod isn't working anymore, solutions? if is possible that don't need delete .minecraft, i have a lot of things and don't want have to restore everything, step by step

**Comment by AlsoSylv** [comment]
Create a new issue with a log file attached
