### ISSUE TITLE
Performance reduction even when all of continuity options are disabled

### ISSUE THREAD

**Issue by Taiyou06** [PepperCode1/Continuity#404]
In a scene with bunch of display entities fps is almost halved, example:

With Continuity (every option is disabled)
https://spark.lucko.me/UzjwEsyHRr
![image](https://github.com/PepperCode1/Continuity/assets/77050201/e4388964-ba04-4978-a104-0695ac2b2c48)

Without Continuity
https://spark.lucko.me/Mz8VZErbFN
![image](https://github.com/PepperCode1/Continuity/assets/77050201/9895972a-f041-4ff7-aa9b-fc40065f7d7c)

**Comment by PepperCode1** [comment]
The main issue here is that rendering items through Indium is somehow significantly slower than not rendering them through Indium. I can't do anything about that. However, I can try to make it so that CTM and emissive models don't say that they have to be rendered through FRAPI (in this case Indium) if the corresponding options are disabled.

**Comment by PepperCode1** [comment]
This should be fixed with 3.0.0-beta.5.
