### ISSUE TITLE
3.0.0 beta 4 for 1.20.2 crashes on 1.20.5+ if block state properties are used

### ISSUE THREAD

**Issue by Tiegertosch** [PepperCode1/Continuity#412]
If you use Continuity with the version of Indium updated for 1.20.6, the game crashes when loading the world. If Continuity is not active, the world loads without any problems

Log: [https://mclo.gs/xV9gM42](https://mclo.gs/xV9gM42)

**Comment by PepperCode1** [comment]
Whether this happens depends on what CTM features your selected resource packs use, which is why it was not caught earlier, but either way it's because Minecraft 1.20.5 changed the return type of a method, resulting in an ABI breaking change. I will make a 1.20.5+ release to fix this as soon as possible and unmark the 1.20.2 version as being compatible with 1.20.5/1.20.6.

**Comment by MiraculixxT** [comment]
Version `3.0.0-beta.4+1.20.2` on Modrinth is still marked to support 1.20.5/6, tho i have the same issues. Resource Pack adds stairs & slabs CTMs and on rendering e.g. `Block{minecraft:waxed_oxidized_cut_copper_slab}[type=double,waterlogged=false]` the game crashes

**Comment by PepperCode1** [comment]
This has been fixed with 3.0.0-beta.5.
