### ISSUE TITLE
Mob glows incorrectly with external resource packs and Complementary shader

### ISSUE THREAD

**Issue by MATRIX-feather** [PepperCode1/Continuity#422]
When used along with *RainbowPixel* and *Complementary* shader, a random mob rendered in the screen will appear glowing, where it shouldn't.

Video about this issue:

https://github.com/PepperCode1/Continuity/assets/55654482/42b6be02-c7a2-4776-b392-6c905025c542

Mods:
- Sodium
- Iris
- FabricAPI
- Continuity

Used resourcepack:
[RainbowPixel v3.5](https://github.com/user-attachments/files/15513914/RainbowPixel.v3.5.zip)

**Comment by PepperCode1** [comment]
Indium is missing from your mod list. Since you have Sodium, if you don't have Indium installed, Continuity will not do anything. Even if you did have it installed, Continuity still does not affect entity rendering in any way, so this is almost certainly an Iris issue or Complementary issue. Try reporting this to Iris.
