### ISSUE TITLE
Can I match against chest content in an easy way? 

### ISSUE THREAD

**Issue by mainrs** [PepperCode1/Continuity#512]
I want to add a custom barrel texture when the barrel is filled with the same item, for example amethyst shards. 

Or predominantly filled. I didn't find anything remotely useful inside optidocs.

**Comment by PepperCode1** [comment]
This is not currently possible and not even theoretically possible to fully support with only Continuity. This is because servers do not send container contents to clients until the container is opened (which can only happen when the player is in range). Since Continuity is a client-side mod, it cannot modify such server logic in a consistent way. Even if it were possible, it could make cheating easier, as well as increasing the amount of network traffic.

**Comment by mainrs** [comment]
Ahh, thanks for the explanation. I was hoping to give my barrels some more life by having some texture variants for barrels filled with items in bulk. The goal was to use these in some kind of warehouse.

Looks like it'll have to end up being a client+server mod.
